# Generated by Django 3.1 on 2020-10-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='desc',
            field=models.TextField(default='', max_length=100),
        ),
    ]
