# Generated by Django 3.1 on 2020-10-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_auto_20201030_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='desc',
            field=models.TextField(default='', max_length=300),
        ),
    ]
