# Generated by Django 3.0.5 on 2020-04-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meals', '0002_meals_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meals',
            options={'verbose_name': 'Meal', 'verbose_name_plural': 'Meals'},
        ),
        migrations.AlterField(
            model_name='meals',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
