# Generated by Django 3.1.1 on 2020-09-25 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
