# Generated by Django 3.1 on 2020-10-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type_of_property',
            field=models.CharField(choices=[('rent', 'rent'), ('sale', 'sale')], max_length=5),
        ),
    ]
