# Generated by Django 3.1 on 2020-10-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20201030_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type_of_property',
            field=models.CharField(choices=[('sale', 'sale'), ('rent', 'rent')], max_length=5),
        ),
    ]
